import type { Metadata } from 'next';
import { getTranslations } from 'next-intl/server';

import { localeHtmlLang, routing, type Locale } from '@/i18n/routing';
import { SITE_URL } from '@/lib/site';

/**
 * Page metadata for the public site (§17).
 *
 * Every public page routes its `generateMetadata` through `pageMetadata` here.
 * The point is that the four things §17 asks for — a unique title and
 * description per page *per locale*, `hreflang` alternates including
 * `x-default`, Open Graph and Twitter cards, and a canonical on every URL —
 * are produced from one place, from one argument: the locale and the path.
 *
 * Getting any of these subtly wrong is invisible in a browser and expensive in
 * search results, which is exactly the kind of thing that should not be
 * retyped per page.
 *
 * ## Why the alternates are built rather than inherited
 *
 * Next merges metadata from layout to page **shallowly**: a page that sets
 * `alternates` replaces the layout's outright, and a page that sets
 * `openGraph` replaces the layout's outright. So partial values in the layout
 * would either be silently dropped or, worse, silently kept — every page would
 * advertise the locale root as its canonical. The layout therefore carries only
 * what is genuinely global (`metadataBase`, the title template, `robots`), and
 * everything URL-shaped is built here, complete, per page.
 */

/**
 * The Open Graph card — `public/og/nusuk-help.png`, generated by
 * `scripts/generate-og-image.js`. One card for both locales; see that file.
 */
const OG_IMAGE = {
  url: '/og/nusuk-help.png',
  width: 1200,
  height: 630,
} as const;

/**
 * Open Graph's `locale` is a territory-qualified tag, not the bare BCP 47 one
 * in `localeHtmlLang`. Saudi Arabia is the market for both.
 */
const OG_LOCALE: Record<Locale, string> = {
  en: 'en_US',
  ar: 'ar_SA',
};

/**
 * The absolute URL of a page in a given locale.
 *
 * `localePrefix: 'always'` (see `i18n/routing.ts`) means every public URL
 * carries its locale and there is no unprefixed variant competing with it —
 * which is what makes one canonical per page per locale unambiguous. The home
 * page is `/en`, not `/en/`: a trailing slash would be a second URL for the
 * same document.
 */
export function localeUrl(locale: string, path: string): string {
  const suffix = path === '/' ? '' : path;
  return `${SITE_URL}/${locale}${suffix}`;
}

/**
 * `hreflang` alternates for a path, in every locale, plus `x-default`.
 *
 * `x-default` points at the English page rather than at a language selector,
 * because there is no selector to point at: `localeDetection` is off (§6), so
 * an unprefixed request lands on `/en` and that is the honest default.
 *
 * Derived from `routing.locales`, so adding a third locale needs no edit here.
 */
function alternateLanguages(path: string): Record<string, string> {
  const languages: Record<string, string> = {};

  for (const locale of routing.locales) {
    languages[localeHtmlLang[locale]] = localeUrl(locale, path);
  }
  languages['x-default'] = localeUrl(routing.defaultLocale, path);

  return languages;
}

type PageMetadataOptions = {
  locale: string;
  /** Locale-less path, exactly as the route map in §4 writes it. `/` for home. */
  path: string;
  /**
   * The page title, from the catalogue.
   *
   * Passed in rather than looked up from a namespace here: the caller already
   * knows which `*.meta` keys are its own, and a convention enforced inside
   * this function would be one more thing to remember about a file that only
   * exists to stop things being forgotten. The copy stays in the catalogue
   * either way, so §19 open item 5 remains a values-only drop.
   */
  title: string;
  description: string;
  /**
   * Set when `title` is already the whole title — the home page, whose
   * `meta.defaultTitle` carries the brand name itself and must not be run
   * through the ` · Nusuk Help` template a second time.
   */
  untemplatedTitle?: boolean;
};

export async function pageMetadata({
  locale,
  path,
  title,
  description,
  untemplatedTitle = false,
}: PageMetadataOptions): Promise<Metadata> {
  const tMeta = await getTranslations({ locale, namespace: 'meta' });

  // Open Graph carries no title template of its own, so the full string is
  // assembled here rather than left to Next — a card reading "About" with no
  // brand name is the failure this avoids.
  const fullTitle = untemplatedTitle
    ? title
    : tMeta('titleTemplate', { page: title });

  const typedLocale = locale as Locale;
  const url = localeUrl(locale, path);

  return {
    // `absolute` stops the layout template appending the brand name to a title
    // that already ends in it.
    title: untemplatedTitle ? { absolute: title } : title,
    description,
    alternates: {
      canonical: url,
      languages: alternateLanguages(path),
    },
    openGraph: {
      type: 'website',
      siteName: tMeta('siteName'),
      title: fullTitle,
      description,
      url,
      locale: OG_LOCALE[typedLocale],
      alternateLocale: routing.locales
        .filter((other) => other !== typedLocale)
        .map((other) => OG_LOCALE[other]),
      images: [{ ...OG_IMAGE, alt: tMeta('siteName') }],
    },
    twitter: {
      card: 'summary_large_image',
      title: fullTitle,
      description,
      images: [OG_IMAGE.url],
    },
  };
}
