import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      ".open-next/**",
      ".wrangler/**",
      "next-env.d.ts",
      // Generated by `wrangler types` — not ours to lint.
      "worker-configuration.d.ts",
    ],
  },
  {
    rules: {
      // §"Conventions": no `any`.
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
  {
    /*
     * `scripts/` holds one-off Node tooling that never reaches the bundle —
     * `generate-og-image.js` builds the Open Graph card and is run by hand. It
     * is plain CommonJS on purpose: `node scripts/…` with no build step, no
     * loader flag, and no `"type": "module"` argument with the Next config.
     * The app's own no-`require` rule is right for `src/` and inapplicable here.
     */
    files: ["scripts/**/*.js"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
];

export default eslintConfig;
